spring:
  application:
    name: challenge-url-shortener
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: shortener-db
      port: 27018
      host: localhost